staticman:
 allowedFields: ['message', 'name']
 branch: master
 commitMessage: "Hey human, here is a new entry."
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "blog/comments/test"
 requiredFields: ['name']