version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    environment:
      - GH_EMAIL: vvrozhkova@gmail.com
      - GH_NAME: Victoria Rozhkova
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: master
      - SOURCE_REPOSITORY_URL: https://github.com/vvrozhkova/testautomation.space.git
      - TARGET_REPOSITORY_URL: https://github.com/vvrozhkova/vvrozhkova.github.io.git

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: |
          if [$CIRCLE_BRANCH == $SOURCE_BRANCH]; then
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

            git clone $TARGET_REPOSITORY_URL out
            cd out
            git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
            git rm -rf .
            cd ..
            gridsome build
            cp -a dist/. out/.
            cd out
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin $TARGET_BRANCH
          fi
